name: gym_frontend
description: "Gym Management Application"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.10.4

dependencies:
  equatable: ^2.0.8
  flutter:
    sdk: flutter
  flutter_spinkit: ^5.2.2
  google_fonts: ^7.0.2
  http: ^1.6.0
  lottie: ^3.3.2
  responsive_builder: ^0.7.1
  shared_preferences: ^2.5.4
  web_socket_channel: ^3.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - lib/assets/animations/
    - lib/assets/images/
    - lib/assets/icons/